### ISSUE TITLE
Following the instructions on README leads to an error

### ISSUE THREAD

**Issue by xrash** [galacticcouncil/sdk#10]
The only thing I did was running `npm install @galacticcouncil/sdk` and then running this code:

```javascript
// Import
const { ApiPromise, WsProvider } = require('@polkadot/api')
const { TradeRouter, PolkadotApiPoolService } = require('@galacticcouncil/sdk')

const main = async () => {

  // Initialize Polkadot API
  const wsProvider = new WsProvider('wss://rpc.basilisk.cloud');
  const api = await ApiPromise.create({ provider: wsProvider });

  // Initialize Trade Router
  const poolService = new PolkadotApiPoolService(api);
  const tradeRouter = new TradeRouter(poolService, { includeOnly: [PoolType.XYK] });

  // Do something
  const result = await tradeRouter.getAllAssets();
  console.log(result);

}

main()
```

I get the following error:

```
node:internal/fs/utils:351
    throw err;
    ^

Error: ENOENT: no such file or directory, open '<...>/node_modules/@galacticcouncil/sdk/dist/hydra_dx_wasm_bg.wasm'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at <...>/node_modules/@galacticcouncil/sdk/dist/index.js:1:4125
    at <...>/node_modules/@galacticcouncil/sdk/dist/index.js:1:222
    at Object.<anonymous> (<...>/node_modules/@galacticcouncil/sdk/dist/index.js:3:169302)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Module.require (node:internal/modules/cjs/loader:1149:19) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '<...>/node_modules/@galacticcouncil/sdk/dist/hydra_dx_wasm_bg.wasm'
}

Node.js v20.1.0
```

**Comment by Denstden** [comment]
Yupp, same for me.

**Comment by nohaapav** [comment]
@Denstden & @xrash Wasm file is not bundled with cjs, only with esm module .. In order to use SDK in cjs (node) you have to include wasm file at project root

**Comment by capjacksparrow42** [comment]
@nohaapav how can we get access to the wasm file? Can you let me know the steps?

**Comment by nohaapav** [comment]
> @nohaapav how can we get access to the wasm file? Can you let me know the steps?

I'll update doc regarding cjs usage week.

**Comment by nohaapav** [comment]
@flipchan Hey, it was never broken, you just have to include wasm at project root in case u using cjs .. Hopefully i can prepare some step by step doc this week ..

**Comment by honglewis** [comment]
@nohaapav There are four directories containing a file named 'hydra_dx_wasm_bg.wasm,' namely 'math-lbp/build,' 'math-omnipool/build,' 'math-stableswap/build,' and 'math-xyk/build.' To make my CJS project work correctly, which one of these should I copy to the project root directory?

**Comment by xabsolon** [comment]
When i copy the wasm file from the following directories: 'math-lbp/build,' 'math-omnipool/build,' 'math-stableswap/build,' and 'math-xyk/build.' It says O.pool_account_name is not a function.

**Comment by michaeldev5** [comment]
Any updates on the documentation regarding CJS usage?

**Comment by flipchan** [comment]
> @nohaapav is this fixed? I get the same error

solved it, all good for me

**Comment by michaeldev5** [comment]
How did you solve it ?

**Comment by flipchan** [comment]
@michaeldev5 will publish the hydradx implemenation opensource soon, I'm using `    "@galacticcouncil/sdk": "^0.6.5",
` with a clean npm cache, works

**Comment by nohaapav** [comment]
Try to upgrade to `1.1.5` or latest .. It should work with commonjs.

**Comment by michaeldev5** [comment]
It works! Many thanks @nohaapav
