### ISSUE TITLE
Calculate spot price preciselly

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/sdk#52]
use wasm functions instead of selling 1 token to determine spot price

- [x] merge and release wasm of https://github.com/galacticcouncil/HydraDX-wasm/pull/31 
- [x] rewrite spot price pool implementations to use wasm functions

**Comment by nohaapav** [comment]
fix in https://github.com/galacticcouncil/sdk/commit/ea39980020bb0fb5cc70977a8183a947fb6b3333
