### ISSUE TITLE
Add additional MRL assets to CROSS-CHAIN UI

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/sdk#53]
Currently we have ETH & DAI in the UI, we also need to ensure that the remaining MRL assets WBTC, USDC & USDT are available in this UI

![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/3169c389-3e2b-4018-8aed-072735915d1f)

**Comment by nohaapav** [comment]
Done
