### ISSUE TITLE
Consider updating PJS packages to v12

### ISSUE THREAD

**Issue by dudo50** [galacticcouncil/sdk#63]
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------
Hey Galacticcouncil team!

We would like to request you to update PJS packages to the latest version v12. We use your SDK in our router and we wish to stay up to date with PJS libs and this SDK prevents us from going latest currently.

Many thanks for prompt resolution in advance!

With kind regards,
Team ParaSpell

**Comment by nohaapav** [comment]
We were waiting for metadata v15 on-chain support in order to do that. 
Btw we'll drop PJS in future entirely, switching to PAPI. Just heads up.

**Comment by dudo50** [comment]
Thanks, @nohaapav , PAPI sounds like an interesting project! We will explore it a little more. Closing this issue for now.

With kind regards,
Team ParaSpell
