### ISSUE TITLE
Update PJS packages to v13

### ISSUE THREAD

**Issue by dudo50** [galacticcouncil/sdk#78]
**Description**
---------------------------------------------------
FEATURE REQUEST
---------------------------------------------------

Hello, we would like to request you to update PJS to v13 as we use Galactic SDK in our XCM Router and this package is the only one preventing us from updating so far (We use unified imports in our monorepo meaning other tools we created cannot be updated as well). As far as I was told, the update from v12 to v13 shouldn't be very complicated. Looking forward to your answer!

Team ParaSpell✨

**Comment by nohaapav** [comment]
@dudo50 Hi, we have some ongoing work on xcm atm but can upgrade next one ;)

**Comment by dudo50** [comment]
Okay, thanks, guys! 

Please ping me once you upgraded so we can upgrade, too :).

With kind regards,
Team ParaSpell✨

**Comment by dudo50** [comment]
cc @nohaapav any progress?

With kind regards,
Team ParaSpell✨

**Comment by nohaapav** [comment]
@dudo50 sry busy with ongoing snowbridge integration. Hopefully soon :) No ETA atm

**Comment by NunoAlexandre** [comment]
@nohaapav Numo from Velocity Labs / Turtle.cool here.

Can you explain exactly what integration work is still pending on Hydra regarding snowbridge? You have already registered their assets and we are able to transfer them directly from Ethereum to Hydra. What exactly is missing? 

Thanks 👌

**Comment by nohaapav** [comment]
> @nohaapav Numo from Velocity Labs / Turtle.cool here.
> 
> Can you explain exactly what integration work is still pending on Hydra regarding snowbridge? You have already registered their assets and we are able to transfer them directly from Ethereum to Hydra. What exactly is missing?
> 
> Thanks 👌

Hi Nuno nothing from your side. Just minor XCM UI upgrade & SDK upgrade. We tested successfully transfer as well on our side for WETH.
