### ISSUE TITLE
Basilisk: Re-enable Robonomics Xchain

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/sdk#82]
Basilisk -> Robonomics route works as is
Robonomics -> Basilisk needs a fix, as Robonomics no longer supports xcm v1
<img width="199" alt="image" src="https://github.com/user-attachments/assets/7ac03567-7cae-44db-9ebd-392d11a854a6">

**Comment by 0xSamsara** [comment]
Hi @green-jay, any update on this?

**Comment by nohaapav** [comment]
> Hi @green-jay, any update on this?

Releasing fix in a bit.

**Comment by 0xSamsara** [comment]
Great, thanks @nohaapav !
