### ISSUE TITLE
Add Darwinia to your service

### ISSUE THREAD

**Issue by fewensa** [galacticcouncil/sdk#83]
Hi team, 
  I'm from Darwinia, we are very interested in your project and hope to support Darwinia chain, RING/USDT and other tokens in your service.
What do I need to do for this or can someone contact me?

Thank you

Related:
- https://github.com/ringecosystem/integration/issues/13
- https://ringdao.com/
- https://darwinia.network/

**Comment by nohaapav** [comment]
Hi @fewensa 
Ideally list all the transfers you want to support with valid extrinsic hash (both directions) so we can recreate the config.

**Comment by fewensa** [comment]
Hi @nohaapav need more information here?

**Comment by nohaapav** [comment]
> Hi @nohaapav need more information here?

All good. We are releasing NEXT version this week so i'll include Darwinia xcm config as well.

**Comment by nohaapav** [comment]
@fewensa Darwinia back online. Closing.
