### ISSUE TITLE
Add myth transfers to sdk

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/sdk#86]
MYTH -> AH <> HYDRATION

**Comment by green-jay** [comment]
hydra -> AH MYTH
`0x6b0d04010100a10f04080100000700e40b5402010100a534000f0000c16ff286230204010002040416040d010000010100d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d00`

AH -> Hydra MYTH
`0x1f0d04010100c91f0404010100a5340013000064a7b3b6e00d0304010100a53404010100a5340304010100a53404040d010000010100d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d00`
