### ISSUE TITLE
Add snowbridge support

### ISSUE THREAD

**Issue by nohaapav** [galacticcouncil/sdk#87]

**Comment by dudo50** [comment]
@nohaapav ,

Is it possible to transfer WETH bridged from SnowBridge to AHP? 
If so, could you please provide us extrinsic that is capable of that?

Thanks!

**Comment by nohaapav** [comment]
> @nohaapav ,
> 
> Is it possible to transfer WETH bridged from SnowBridge to AHP? If so, could you please provide us extrinsic that is capable of that?
> 
> Thanks!

Yes, it's. I'll once tested and configured.

**Comment by nohaapav** [comment]
Done

**Comment by dudo50** [comment]
@nohaapav can you point us to extrinsics that are capable of this? Thanks!
