### ISSUE TITLE
Mythos Transfers between Asset Hub and Hydration

### ISSUE THREAD

**Issue by dudo50** [galacticcouncil/sdk#95]
Hello, we have been contacted with a request for MYTH asset transfers from Asset Hub Polkadot directly to Hydration within one XCM. Currently, we haven't found a successful case for this scenario anywhere (The scenario is not present in the Hydration app either). Are these transfers possible? If yes, could you please point us to the correct extrinsic that can achieve such transfer? Also, if they are not is the support planned? Currently the only way we know of is to transfer the assets from Asset Hub directly into Mythos and then redirect them to Hydration from Mythos.

Thank you for your time.

With kind regards,
Team ParaSpell

**Comment by green-jay** [comment]
Currently this is problematic hence we don't allow in in our UI. It should become viable once XCMv5 is deployed.
